export const books = [
  {
    id: 1,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    img: "https://example.com/the-great-gatsby.jpg",
    category: "Classic",
    state: "wantToRead",
  },
  {
    id: 2,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    img: "https://example.com/to-kill-a-mockingbird.jpg",
    category: "Classic",
    state: "read",
  },
  {
    id: 3,
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    img: "https://example.com/harry-potter-philosophers-stone.jpg",
    category: "Fantasy",
    state: "none",
  },
  {
    id: 4,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    img: "https://example.com/the-hobbit.jpg",
    category: "Fantasy",
    state: "read",
  },
  {
    id: 5,
    title: "1984",
    author: "George Orwell",
    img: "https://example.com/1984.jpg",
    category: "Dystopian",
    state: "none",
  },
  {
    id: 6,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    img: "https://example.com/pride-and-prejudice.jpg",
    category: "Classic",
    state: "wantToRead",
  },
  {
    id: 7,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    img: "https://example.com/the-catcher-in-the-rye.jpg",
    category: "Classic",
    state: "currentlyReading",
  },
  {
    id: 8,
    title: "To the Lighthouse",
    author: "Virginia Woolf",
    img: "https://example.com/to-the-lighthouse.jpg",
    category: "Classic",
    state: "none",
  },
  {
    id: 9,
    title: "The Alchemist",
    author: "Paulo Coelho",
    img: "https://example.com/the-alchemist.jpg",
    category: "Fiction",
    state: "WantToRead",
  },
  {
    id: 10,
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    img: "https://example.com/the-lord-of-the-rings.jpg",
    category: "Fantasy",
    state: "read",
  },
  {
    id: 11,
    title: "Moby-Dick",
    author: "Herman Melville",
    img: "https://example.com/moby-dick.jpg",
    category: "Classic",
    state: "currentlyReading",
  },
  {
    id: 12,
    title: "Brave New World",
    author: "Aldous Huxley",
    img: "https://example.com/brave-new-world.jpg",
    category: "Dystopian",
    state: "none",
  },
  {
    id: 13,
    title: "The Odyssey",
    author: "Homer",
    img: "https://example.com/the-odyssey.jpg",
    category: "Classic",
    state: "none",
  },
  {
    id: 14,
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    img: "https://example.com/crime-and-punishment.jpg",
    category: "Classic",
    state: "none",
  },
  {
    id: 15,
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    img: "https://example.com/the-picture-of-dorian-gray.jpg",
    category: "Classic",
    state: "currentlyReading",
  },
  {
    id: 16,
    title: "Jane Eyre",
    author: "Charlotte Bronte",
    img: "https://example.com/jane-eyre.jpg",
    category: "Classic",
    state: "read",
  },
  {
    id: 17,
    title: "The Hunger Games",
    author: "Suzanne Collins",
    img: "https://example.com/the-hunger-games.jpg",
    category: "Dystopian",
    state: "none",
  },
  {
    id: 18,
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    img: "https://example.com/the-kite-runner.jpg",
    category: "Fiction",
    state: "none",
  },
  {
    id: 19,
    title: "One Hundred Years of Solitude",
    author: "Gabriel Garcia Marquez",
    img: "https://example.com/one-hundred-years-of-solitude.jpg",
    category: "Classic",
    state: "wantToRead",
  },
  {
    id: 20,
    title: "The Chronicles of Narnia",
    author: "C.S. Lewis",
    img: "https://example.com/the-chronicles-of-narnia.jpg",
    category: "Fantasy",
    state: "read",
  },
];
